"""add response api to whatsapp alert log

Revision ID: 0e736e1e6969
Revises: cff57d9ed210
Create Date: 2026-05-13 20:56:09.693979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e736e1e6969'
down_revision = 'cff57d9ed210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_alert_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_api', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_alert_log', schema=None) as batch_op:
        batch_op.drop_column('response_api')

    # ### end Alembic commands ###
