"""initial gigamas clean

Revision ID: cf456bc5496c
Revises: 
Create Date: 2026-05-12 20:23:48.616454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf456bc5496c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_barang', sa.String(length=150), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('satuan', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_barang')
    )
    op.create_table('cabang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_cabang', sa.String(length=150), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_cabang')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_supplier', sa.String(length=150), nullable=False),
    sa.Column('kontak', sa.String(length=100), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_supplier')
    )
    op.create_table('stock_cabang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barang_id', sa.Integer(), nullable=False),
    sa.Column('cabang_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], ),
    sa.ForeignKeyConstraint(['cabang_id'], ['cabang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barang_id', 'cabang_id', name='uix_barang_cabang')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status_aktif', sa.Boolean(), nullable=True),
    sa.Column('cabang_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cabang_id'], ['cabang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barang_id', sa.Integer(), nullable=False),
    sa.Column('cabang_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(length=20), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], ),
    sa.ForeignKeyConstraint(['cabang_id'], ['cabang.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    op.drop_table('users')
    op.drop_table('stock_cabang')
    op.drop_table('supplier')
    op.drop_table('cabang')
    op.drop_table('barang')
    # ### end Alembic commands ###
