"""update models gigamas final

Revision ID: cff57d9ed210
Revises: cf456bc5496c
Create Date: 2026-05-12 21:24:49.332948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff57d9ed210'
down_revision = 'cf456bc5496c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_alert_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_tujuan', sa.String(length=50), nullable=False),
    sa.Column('nama_tujuan', sa.String(length=150), nullable=True),
    sa.Column('kategori_alert', sa.String(length=100), nullable=False),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('transaksi_id', sa.Integer(), nullable=True),
    sa.Column('cabang_id', sa.Integer(), nullable=True),
    sa.Column('barang_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], ),
    sa.ForeignKeyConstraint(['cabang_id'], ['cabang.id'], ),
    sa.ForeignKeyConstraint(['transaksi_id'], ['transaksi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stok_minimum', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stok_kritis', sa.Integer(), nullable=True))

    with op.batch_alter_table('cabang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kontak', sa.String(length=100), nullable=True))

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor_whatsapp', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('menerima_alert', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('menerima_alert')
        batch_op.drop_column('nomor_whatsapp')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('cabang', schema=None) as batch_op:
        batch_op.drop_column('kontak')

    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_column('stok_kritis')
        batch_op.drop_column('stok_minimum')

    op.drop_table('whatsapp_alert_log')
    # ### end Alembic commands ###
